site_name: odp
repo_url: https://github.com/open-data-products/odp
site_url: https://open-data-products.github.io/odp
site_description: odp
site_author: odp Authors
edit_uri: edit/main/docs/
repo_name: open-data-products/odp
copyright: Maintained by <a href="https://open-data-products.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-data-products/odp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/odp

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
